### ISSUE TITLE
2FA with Apple ID

### ISSUE THREAD

**Issue by dataviruset** [sinoru/actions-setup-xcode#92]
Got this error message after killing the `xcversion update` command manually on my CI machine after it got stuck for several minutes. Turns out that I couldn't log in to the Apple ID without 2FA.
```
Run sinoru/actions-setup-xcode@v2
/usr/local/bin/xcversion select 13.2.1
[!] Version 13.2.1 not installed.
Warning: Xcode 13.2.1 not avilable in local.
Install Xcode
  /usr/local/bin/xcversion update
  Two-factor Authentication (6 digits code) is enabled for account '<redacted>'
  More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915
  
  If you're running this in a non-interactive session (e.g. server or CI)
  check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
  
  Please enter the 6 digit code you received at <redacted>:
  Error: The process '/usr/local/bin/xcversion' failed with exit code null
```

The problem is described further in this link: https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
I suggest this project to add the `SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA` environment variable as described in https://docs.fastlane.tools/best-practices/continuous-integration/ so at least the builds won't get stuck asking for a verification code.
I see `SPACESHIP_SKIP_2FA_UPGRADE` is already added which is good so verification code inputs are avoided if they aren't needed.

**Comment by sinoru** [comment]
It might be related to self-hosted runner, which I know fastlane will invoke SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA, when in CI env. (Which has CI=true in shell env)

Anyway, I will adds that value which seems good.

Thanks to report :)

**Comment by dataviruset** [comment]
Thanks a lot :)
